---
  - name: ensure file exists
    copy:
      content: "options nf_conntrack hashsize=1193572"
      dest: /etc/modprobe.d/nf_conntrack.conf
      force: no

  - name: sysctl.conf
    lineinfile:
      dest: /etc/sysctl.conf
      line: '{{ item }}'
    with_items:
      - 'net.ipv4.ip_forward=1'
      - 'net.ipv4.neigh.default.gc_thresh1 = 4096'
      - 'net.ipv4.neigh.default.gc_thresh2 = 8192'
      - 'net.ipv4.neigh.default.gc_thresh3 = 12288'
      - 'net.ipv4.netfilter.ip_conntrack_max=1572864'
      - 'net.netfilter.nf_conntrack_max = 1572864'
      - 'net.netfilter.nf_conntrack_generic_timeout = 300'
      - 'net.netfilter.nf_conntrack_tcp_timeout_syn_sent = 60'
      - 'net.netfilter.nf_conntrack_tcp_timeout_syn_recv = 60'
      - 'net.netfilter.nf_conntrack_tcp_timeout_established = 600'
      - 'net.netfilter.nf_conntrack_tcp_timeout_fin_wait = 60'
      - 'net.netfilter.nf_conntrack_tcp_timeout_close_wait = 45'
      - 'net.netfilter.nf_conntrack_tcp_timeout_last_ack = 30'
      - 'net.netfilter.nf_conntrack_tcp_timeout_time_wait = 120'
      - 'net.netfilter.nf_conntrack_tcp_timeout_close = 10'
      - 'net.netfilter.nf_conntrack_tcp_timeout_max_retrans = 300'
      - 'net.netfilter.nf_conntrack_tcp_timeout_unacknowledged = 300'
      - 'net.netfilter.nf_conntrack_udp_timeout = 30'
      - 'net.netfilter.nf_conntrack_udp_timeout_stream = 60'
      - '#net.netfilter.nf_conntrack_icmpv6_timeout = 30'
      - 'net.netfilter.nf_conntrack_icmp_timeout = 30'
      - 'net.netfilter.nf_conntrack_events_retry_timeout = 15'
      - 'net.netfilter.nf_conntrack_checksum=0'
      - 'net.ipv4.netfilter.ip_conntrack_checksum=0'
      - 'net.core.dev_weight = 16'
      - 'net.core.netdev_budget = 256'
      - 'net.core.netdev_max_backlog = 16000'
      - 'vm.swappiness = 10'
      - 'vm.dirty_background_ratio = 5'
      - 'vm.dirty_ratio = 10'

  - name: add nf_conntrack
    command: "modprobe nf_conntrack"

  - name: add nf_conntrack_ipv4
    command: "modprobe nf_conntrack_ipv4"

  - name: sysctl -p
    command: "sysctl -p"
